version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: customer_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  mock-server:
    build:
      context: ./mock-server   # ✅ MUST be like this
    ports:
      - "5000:5000"

  pipeline-service:
    build:
      context: ./pipeline-service   # ✅ FIX HERE
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - mock-server
    restart: always